### ISSUE TITLE
unqualified exec is not allowed in function 'compile_parser'

### ISSUE THREAD

**Issue by uludag** [JohnLonginotto/pybam#3]
> exec(code,exec_dict) in globals(), locals()  

Unless I add `in globals(), locals() ` bits to the above line (line 585, pybam.py), I get the following error:

> SyntaxError: unqualified exec is not allowed in function 'compile_parser' it contains a nested function with free variables

I found this workaround on the following discussion:
http://stackoverflow.com/questions/4484872/in-python-why-doesnt-exec-work-in-a-function-with-a-subfunction
I was using Python 2.7.5

--mahmut

**Comment by JohnLonginotto** [comment]
Thank you very much for this uludag! It appears this is due to a bug in CPython up until 2.7.8 before being fixed in 2014: https://bugs.python.org/issue21591

However, I'm sure many people will want to use pybam on much old interpreters than 2.7.8, so i will modify the code with your fix :) Thank again uludag!
